<?php
declare(strict_types=1);

// MixpanelAnnotations SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelAnnotationsUtility::setRegistrar(function (MixpanelAnnotationsUtility $u): void {
    $u->clean = [MixpanelAnnotationsClean::class, 'call'];
    $u->done = [MixpanelAnnotationsDone::class, 'call'];
    $u->make_error = [MixpanelAnnotationsMakeError::class, 'call'];
    $u->feature_add = [MixpanelAnnotationsFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelAnnotationsFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelAnnotationsFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelAnnotationsFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelAnnotationsMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelAnnotationsMakeContext::class, 'call'];
    $u->make_options = [MixpanelAnnotationsMakeOptions::class, 'call'];
    $u->make_request = [MixpanelAnnotationsMakeRequest::class, 'call'];
    $u->make_response = [MixpanelAnnotationsMakeResponse::class, 'call'];
    $u->make_result = [MixpanelAnnotationsMakeResult::class, 'call'];
    $u->make_point = [MixpanelAnnotationsMakePoint::class, 'call'];
    $u->make_spec = [MixpanelAnnotationsMakeSpec::class, 'call'];
    $u->make_url = [MixpanelAnnotationsMakeUrl::class, 'call'];
    $u->param = [MixpanelAnnotationsParam::class, 'call'];
    $u->prepare_auth = [MixpanelAnnotationsPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelAnnotationsPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelAnnotationsPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelAnnotationsPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelAnnotationsPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelAnnotationsPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelAnnotationsPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelAnnotationsGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelAnnotationsGraphql::class, 'errors'];
    $u->result_basic = [MixpanelAnnotationsResultBasic::class, 'call'];
    $u->result_body = [MixpanelAnnotationsResultBody::class, 'call'];
    $u->result_headers = [MixpanelAnnotationsResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelAnnotationsTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelAnnotationsTransformResponse::class, 'call'];
});
